version: '3.4'

networks:
  frontend:
  backend:


services:
  mssqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment:
      ACCEPT_EULA: Y 
      SA_PASSWORD: Sa!Event
      TZ: "America/Los_Angeles"
    ports:
      - "5040:1433"
    container_name: MSSQLContainer   
    networks:
      - backend

  event:
    image: eventmanagement/eventapi
    build:
      context: .\EventAPI
      dockerfile: Dockerfile
    environment:
      DatabaseServer: mssqlserver
      DatabaseName: EventCatalogDb
      DatabaseUser: sa
      DatabasePassword: Sa!Event
      ExternalCatalogUrl: http://localhost:7000
      TZ: "America/Los_Angeles"
    ports:
      - "7000:80"
    container_name: EventCatalogAPIContainer  
    networks:
      - frontend
      - backend
    depends_on:
      - mssqlserver

  webmvc:
    image: events/webmvc
    build:
      context: .\WebMvc
      dockerfile: Dockerfile
    environment:
      CatalogUrl: http://event
      TZ: "America/Los_Angeles"
    ports:
      - "7500:80"
    container_name: WebMVCContainer
    networks:
      - frontend
    depends_on:
      - event